<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="13">

  <testsuite name="reg"
    errors="0" failures="1" hostname="" id="" package="reg" skipped="0"
    tests="13" time="0.000" timestamp="Thu, 29 Oct 2015 08:55:15 GMT">
  
    <testcase name="init" time="5.141" assertions="2">

    

    
    </testcase>
  
    <testcase name="eligible" time="0.1880" assertions="3">

    

    

    
    </testcase>
  
    <testcase name="names" time="0.9450" assertions="9">

    

    

    

    

    

    

    

    

    
    </testcase>
  
    <testcase name="address" time="1.067" assertions="12">

    

    

    

    

    

    

    

    

    

    

    

    
    </testcase>
  
    <testcase name="contact" time="0.6310" assertions="6">

    

    

    

    

    

    
    </testcase>
  
    <testcase name="desired work" time="1.035" assertions="9">

    

    

    

    

    

    

    

    

    
    </testcase>
  
    <testcase name="transport" time="0.3520" assertions="6">

    

    

    

    

    

    
    </testcase>
  
    <testcase name="emergency contact" time="0.3760" assertions="6">

    

    

    

    

    

    
    </testcase>
  
    <testcase name="income" time="0.4010" assertions="6">

    

    

    

    

    

    
    </testcase>
  
    <testcase name="cv" time="0.1470" assertions="2">

    

    
    </testcase>
  
    <testcase name="terms" time="0.2960" assertions="4">

    

    

    

    
    </testcase>
  
    <testcase name="submit" time="1.452" assertions="5">

      <failure message="Form successful">    at Object.module.exports.submit (/Users/john/dev/hrgo-tests/tests/reg/reg.js:140:15)
    at Module.call (/usr/local/lib/node_modules/nightwatch/lib/runner/module.js:60:34)
    at /usr/local/lib/node_modules/nightwatch/lib/runner/testcase.js:96:29
    at _fulfilled (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)</failure>

      <failure message="Testing if element &lt;div .sweet-alert .success&gt; is visible.">    at Object.module.exports.submit (/Users/john/dev/hrgo-tests/tests/reg/reg.js:141:15)
    at Module.call (/usr/local/lib/node_modules/nightwatch/lib/runner/module.js:60:34)
    at /usr/local/lib/node_modules/nightwatch/lib/runner/testcase.js:96:29
    at _fulfilled (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)</failure>

    

      <failure message="we are back home">    at Object.module.exports.submit (/Users/john/dev/hrgo-tests/tests/reg/reg.js:144:15)
    at Module.call (/usr/local/lib/node_modules/nightwatch/lib/runner/module.js:60:34)
    at /usr/local/lib/node_modules/nightwatch/lib/runner/testcase.js:96:29
    at _fulfilled (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)</failure>

    
    </testcase>
  
    <testcase name="end" time="0.1920" assertions="0">
    </testcase>
  
  
  </testsuite>
</testsuites>
